name: 🔧 Build -> Package 📦
on: [push, pull_request]

env:
  GODOT_VERSION: '4'
  GODOT_CPP: 'godot-cpp'

jobs:
  static-checks:
    name: 📊 Static Checks (clang-format, black format, file format)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -qq dos2unix recode clang-format-11
          sudo update-alternatives --remove-all clang-format
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-11 100
          sudo pip3 install black==20.8b1 pygments

      - name: File formatting checks (file_format.sh)
        run: |
          bash ./misc/scripts/file_format.sh

      - name: Style checks via clang-format (clang_format.sh)
        run: |
          bash ./misc/scripts/clang_format.sh

      - name: Python style checks via black (black_format.sh)
        run: |
          bash ./misc/scripts/black_format.sh

  build:
    runs-on: ${{ matrix.os }}
    name: 🔧 Build
    needs: static-checks
    strategy:
      fail-fast: false
      matrix:
        include:
#          # Android
#          - platform: android
#            arch: 'x86'
#            sconsflags: 'android_arch=x86'
#            os: 'ubuntu-20.04'
#          - platform: android
#            arch: 'x64'
#            sconsflags: 'android_arch=x86_64'
#            os: 'ubuntu-20.04'
#          - platform: android
#            arch: 'arm'
#            sconsflags: 'android_arch=armv7'
#            os: 'ubuntu-20.04'
#          - platform: android
#            arch: 'arm64'
#            sconsflags: 'android_arch=arm64v8'
#            os: 'ubuntu-20.04'
#
#          # iOS
#          - platform: ios
#            arch: 'x64'
#            sconsflags: 'ios_arch=x86_64 ios_simulator=true'
#            os: 'macos-latest'
#          - platform: ios
#            arch: 'arm64'
#            sconsflags: 'ios_arch=arm64'
#            os: 'macos-11'
#
#          # Linux
#          - platform: linux
#            arch: 'x86'
#            sconsflags: 'bits=32'
#            os: 'ubuntu-20.04'
#          - platform: linux
#            arch: 'x64'
#            sconsflags: 'bits=64'
#            os: 'ubuntu-20.04'
#
#          # macOS
#          - platform: osx
#            arch: 'x64'
#            sconsflags: 'bits=64 macos_arch=x86_64'
#            os: 'macos-11'
#          - platform: osx
#            arch: 'arm64'
#            sconsflags: 'bits=64 macos_arch=arm64'
#            os: 'macos-11'

          # Windows
          - platform: windows
            arch: 'x86'
            sconsflags: 'bits=32 use_mingw=yes build_library=no'
            os: 'ubuntu-20.04'
            msvc_arch: amd64_x86
          - platform: windows
            arch: 'x64'
            sconsflags: 'bits=64 use_mingw=yes build_library=no'
            os: 'ubuntu-20.04'
            msvc_arch: amd64

    env:
      SCONSFLAGS: ${{ matrix.sconsflags }} platform=${{ matrix.platform }} --jobs=2

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Windows build dependencies
        if: ${{ matrix.platform == 'windows' }}
        run: |
          sudo apt-get install build-essential mingw-w64

      - name: Install Linux build dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get install build-essential gcc-multilib wget g++-multilib

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version
          cmake --version

      - name: Compilation ${{ matrix.platform }} - ${{ matrix.arch }} - debug
        run: |
          scons target=debug generate_bindings=yes godot_version=${GODOT_VERSION}

      - name: Compilation ${{ matrix.platform }} - ${{ matrix.arch }} - release
        run: |
          scons target=release godot_version=${GODOT_VERSION}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: bin/*

  package:
    name: 📦 Package
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Package artifacts for release
        run: |
          mkdir release
          cd release
          for name in webrtc webrtc_debug
          do
            mkdir -p ${name}/lib/
            find ../artifacts -wholename "*/${name}/lib/*" | xargs cp -t ${name}/lib/
            find ../artifacts -wholename "*/${name}/${name}.tres" | head -n 1 | xargs cp -t ${name}/
          done

          zip -r godot-webrtc-native-release.zip webrtc
          zip -r godot-webrtc-native-debug.zip webrtc_debug
          ls -R

      - uses: actions/upload-artifact@v2
        with:
          name: godot-webrtc-native-debug.zip
          path: release/godot-webrtc-native-debug.zip

      - uses: actions/upload-artifact@v2
        with:
          name: godot-webrtc-native-release.zip
          path: release/godot-webrtc-native-release.zip
